server:
  port: 8890

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/Developer/IdeaProjects/eden/h2/h2_test
    username: root
    password: 123456

  h2:
    console:
      enabled: true
      path: /h2-console

# 日志配置
logging:
  file:
    name: logs/${spring.application.name}.log # 日志文件名
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB
  level:
    com:
      bebop: DEBUG