server:
  port: 8889

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&CharacterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 612330ZfzF
  #thymeleaf
  thymeleaf:
    cache: false


#mybatis
mybatis:
  type-aliases-package: com.bebop.model
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  file:
    name: logs/${spring.application.name}.log # 日志文件名
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB
  level:
    com:
      bebop: DEBUG